name: Run Colab Notebook

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
      - name: Run Colab Notebook
        run: |
          curl -X POST "https://colab.research.google.com/drive/1qT0pfA9Z7Wh60QHc-Lad5HJSmZWNVt6d/execute"
